export const SELECT_ABOUT_DESKTOP = 'SELECT_ABOUT_DESKTOP';
export const SELECT_PORT_DESKTOP = 'SELECT_PORT_DESKTOP';

export const SELECT_HAM_MOBILE = 'SELECT_HAM_MOBILE';
export const SELECT_ABOUT_MOBILE = 'SELECT_ABOUT_MOBILE';
export const SELECT_PORT_MOBILE = 'SELECT_PORT_MOBILE';
